version: "3"

services:
  reverse-proxy:
    container_name: reverse-proxy
    build: .
    ports:
      - "80:80"
    environment:
      app: "http://localhost:80"
      api: "http://localhost:8080"
